<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Attendance Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 10pt;
        }

        h1 {
            text-align: center;
            font-size: 16pt;
            margin-bottom: 5px;
        }

        .report-period {
            text-align: center;
            font-size: 10pt;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        table,
        th,
        td {
            border: 1px solid black;
            padding: 6px;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        td {
            text-align: left;
        }

        .page-footer {
            text-align: center;
            font-size: 8pt;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <h1>Attendance Report</h1>
    <div class="report-period">
        <strong>Report Period:</strong>
        {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} to
        {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Employee Name</th>
                <th>Employee ID</th>
                <th>Attendance</th>
                <th>Half Day</th>
                <th>Date</th>
                <th>In Time</th>
                <th>Out Time</th>
                <th>Branch</th>
                <th>Department</th>
                <th>Company</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($attendances as $attendance)
                <tr>
                    <td>{{ $attendance->employee->name ?? 'N/A' }}</td>
                    <td>{{ $attendance->employee->emp_id ?? 'N/A' }}</td>
                    <td>{{ $attendance->attendance }}</td>
                    <td>{{ $attendance->halfday }}</td>
                    <td>{{ \Carbon\Carbon::parse($attendance->date)->format('Y-m-d') }}</td>
                    <td>{{ $attendance->in_time ? \Carbon\Carbon::parse($attendance->in_time)->format('H:i:s') : 'N/A' }}
                    </td>
                    <td>{{ $attendance->out_time ? \Carbon\Carbon::parse($attendance->out_time)->format('H:i:s') : 'N/A' }}
                    </td>
                    <td>{{ $attendance->branch->branch_name ?? 'N/A' }}</td>
                    <td>{{ $attendance->department->name ?? 'N/A' }}</td>
                    <td>{{ $attendance->employee->company->company_name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- <div class="page-footer">
        <p>Generated by {{ config('app.name') }} | {{ date('Y') }}</p>
    </div> -->
</body>

</html>
