<!-- resources/views/user/reports/pdf_employee.blade.php -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 10px;
            font-size: 8pt;
        }

        h1 {
            text-align: center;
            font-size: 12pt;
            margin-bottom: 10px;
        }

        .report-dates {
            text-align: center;
            font-size: 8pt;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        table,
        th,
        td {
            border: 1px solid #000;
            padding: 4px;
        }

        th {
            background-color: #f2f2f2;
            font-size: 8pt;
        }

        td {
            font-size: 7.5pt;
            word-wrap: break-word;
        }

        .page-footer {
            text-align: center;
            font-size: 7pt;
            margin-top: 10px;
        }
    </style>

</head>

<body>
    <h1>Employee Report</h1>
    <div class="report-dates">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} to
        {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
    </div>
    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Salary</th>
                <th>Join Date</th>
                <th>Branch</th>
                <th>Department</th>
                <th>Company</th>


            </tr>
        </thead>
        <tbody>
            @foreach ($employees as $employee)
                <tr>
                    <td>{{ $employee['emp_id'] }}</td>
                    <td>{{ $employee['name'] }}</td>
                    <td>{{ $employee['email'] }}</td>
                    <td>{{ $employee['phone'] }}</td>
                    <td>{{ $employee['position'] }}</td>
                    <td>{{ $employee['salary'] }}</td>
                    <td>{{ $employee['created_at'] }}</td>
                    <td>{{ $employee['branch_name'] }}</td>
                    <td>{{ $employee['department_name'] }}</td>
                    <td>{{ $employee['company_name'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- <div class="page-footer">
        <p>Generated by {{ config('app.name') }} | {{ date('Y') }}</p>
    </div> -->
</body>

</html>
