<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Leave Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            margin: 20px;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        .report-details {
            text-align: center;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 10px;
        }

        table,
        th,
        td {
            border: 1px solid #000;
        }

        th {
            background-color: #f4f4f4;
            text-align: center;
        }

        td {
            padding: 6px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 9px;
        }
    </style>
</head>

<body>

    <h2>Leave Report</h2>

    <div class="report-details">
        <strong>Company:</strong> {{ $companyName }} <br>
        <strong>Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} to
        {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Leave Type</th>
                <th>From Date</th>
                <th>To Date</th>
                <th>Reason</th>
                <th>Days</th>
                <th>Status</th>
                <th>Branch</th>
                <th>Department</th>
                <th>Company</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($leaves as $leave)
                <tr>
                    <td>{{ $leave->employee->emp_id ?? 'N/A' }}</td>
                    <td>{{ $leave->employee->name ?? 'N/A' }}</td>
                    <td>
                        @switch($leave->leave_type)
                            @case(1)
                                Casual Leave
                            @break

                            @case(2)
                                Sick Leave
                            @break

                            @case(3)
                                Privileged Leave
                            @break

                            @default
                                N/A
                        @endswitch
                    </td>
                    <td>{{ \Carbon\Carbon::parse($leave->from_date)->format('Y-m-d') }}</td>
                    <td>{{ \Carbon\Carbon::parse($leave->to_date)->format('Y-m-d') }}</td>
                    <td>{{ $leave->reason }}</td>
                    <td>{{ $leave->days }}</td>
                    <td>{{ $leave->status }}</td>
                    <td>{{ $leave->branch->branch_name ?? 'N/A' }}</td>
                    <td>{{ $leave->department->name ?? 'N/A' }}</td>
                    <td>{{ $leave->employee->company->company_name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <!-- <div class="footer">
        Generated by {{ config('app.name') }} | {{ now()->format('Y') }}
    </div> -->

</body>

</html>
